"""
Generic FastAPI service agent server.
DO NOT EDIT this file — configure your agent in agent/prompts.py and agent/tools.py.
Port and name are set in config.yaml and injected by start.sh.
"""

import json
import uuid
from datetime import datetime
from typing import Any

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from agent.gemini_agent import ServiceAgent

# These are overridden by the AGENT_NAME / AGENT_DESCRIPTION env vars set in start.sh
import os
_AGENT_NAME = os.environ.get("AGENT_NAME", "service-agent")
_AGENT_DESCRIPTION = os.environ.get("AGENT_DESCRIPTION", "A Gemini-powered service agent")

app = FastAPI(
    title=f"{_AGENT_NAME} API",
    description=_AGENT_DESCRIPTION,
    version="1.0.0",
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

_sessions: dict[str, dict[str, Any]] = {}
_agent: ServiceAgent | None = None


def get_agent() -> ServiceAgent:
    global _agent
    if _agent is None:
        _agent = ServiceAgent()
    return _agent


class SessionResponse(BaseModel):
    session_id: str
    created_at: str
    updated_at: str
    message_count: int


class MessageRequest(BaseModel):
    message: str
    stream: bool = False


class MessageResponse(BaseModel):
    session_id: str
    response: str
    history_length: int


@app.get("/health")
async def health():
    return {"status": "ok", "agent": _AGENT_NAME, "sessions": len(_sessions), "model": ServiceAgent.MODEL}


@app.post("/sessions", response_model=SessionResponse)
async def create_session():
    sid = str(uuid.uuid4())
    now = datetime.utcnow().isoformat() + "Z"
    _sessions[sid] = {"history": [], "created_at": now, "updated_at": now}
    return SessionResponse(session_id=sid, created_at=now, updated_at=now, message_count=0)


@app.get("/sessions/{session_id}", response_model=SessionResponse)
async def get_session(session_id: str):
    if session_id not in _sessions:
        raise HTTPException(404, "Session not found")
    sess = _sessions[session_id]
    count = sum(
        1 for m in sess["history"]
        if m["role"] in ("user", "model") and any("text" in p for p in m.get("parts", []))
    )
    return SessionResponse(session_id=session_id, created_at=sess["created_at"],
                           updated_at=sess["updated_at"], message_count=count)


@app.get("/sessions/{session_id}/history")
async def get_history(session_id: str):
    if session_id not in _sessions:
        raise HTTPException(404, "Session not found")
    return {"session_id": session_id, "history": _sessions[session_id]["history"]}


@app.delete("/sessions/{session_id}")
async def delete_session(session_id: str):
    if session_id not in _sessions:
        raise HTTPException(404, "Session not found")
    del _sessions[session_id]
    return {"status": "deleted", "session_id": session_id}


@app.post("/sessions/{session_id}/messages")
async def send_message(session_id: str, body: MessageRequest):
    """
    Send a message. stream=true returns SSE; stream=false returns JSON.

    SSE event types:
      {"type": "tool_call",   "name": "...", "args": {...}}
      {"type": "tool_result", "name": "...", "result": "..."}
      {"type": "text",        "content": "..."}
      {"type": "done"}
      {"type": "error",       "message": "..."}
    """
    if session_id not in _sessions:
        raise HTTPException(404, "Session not found")

    sess = _sessions[session_id]
    agent = get_agent()

    if body.stream:
        async def event_stream():
            updated = sess["history"]
            try:
                async for event in agent.stream_chat(sess["history"], body.message):
                    if event["type"] == "text":
                        updated = event.pop("history", updated)
                    yield f"data: {json.dumps(event)}\n\n"
                sess["history"] = updated
                sess["updated_at"] = datetime.utcnow().isoformat() + "Z"
            except Exception as e:
                yield f"data: {json.dumps({'type': 'error', 'message': str(e)})}\n\n"
                yield f"data: {json.dumps({'type': 'done'})}\n\n"

        return StreamingResponse(
            event_stream(),
            media_type="text/event-stream",
            headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
        )

    try:
        text, updated = agent.chat(sess["history"], body.message)
    except Exception as e:
        raise HTTPException(500, str(e))
    sess["history"] = updated
    sess["updated_at"] = datetime.utcnow().isoformat() + "Z"
    return MessageResponse(session_id=session_id, response=text, history_length=len(updated))


@app.post("/chat")
async def stateless_chat(body: MessageRequest):
    """Stateless single-turn chat (no session history)."""
    agent = get_agent()
    try:
        text, _ = agent.chat([], body.message)
    except Exception as e:
        raise HTTPException(500, str(e))
    return {"response": text}


@app.get("/chat")
async def stateless_chat_get(message: str):
    """
    Stateless GET — used by the responder dispatcher.
    Returns plain text so overlay replies are human-readable.
    """
    agent = get_agent()
    try:
        text, _ = agent.chat([], message)
    except Exception as e:
        raise HTTPException(500, str(e))
    return text
