"""
Generic TUI for service agents.
DO NOT EDIT this file — configure your agent in agent/prompts.py and agent/tools.py.
Agent name and port are injected via environment variables set by start.sh.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys

import httpx
from rich.console import Console
from rich.markdown import Markdown
from rich.padding import Padding

_NAME = os.environ.get("AGENT_NAME", "service-agent")
_DEFAULT_PORT = int(os.environ.get("AGENT_PORT", "8000"))
_DEFAULT_API_URL = f"http://localhost:{_DEFAULT_PORT}"

_console = Console(highlight=False, markup=True)


def _log(name: str, message: str, level: str = "info") -> None:
    markers = {"success": "[green]✓[/green]", "error": "[red]✗[/red]", "warning": "[yellow]![/yellow]"}
    _console.print(f"  {markers.get(level, '[dim]⏺[/dim]')} {name}  {message}")


def _sys(text: str) -> None:
    for line in text.splitlines():
        _console.print(f"  [dim]{line}[/dim]")


def _print_welcome(api_url: str) -> None:
    _console.print()
    _sys(f"{_NAME}  ·  {api_url}")
    _sys("/new  new session    /clear  clear screen    /quit  exit")
    _console.print()


def _print_agent(text: str) -> None:
    _console.print()
    _console.print(f"  [bold]{_NAME}[/bold]")
    _console.print(Padding(Markdown(text), pad=(0, 4, 0, 2)))
    _console.print()


class AgentClient:
    def __init__(self, api_url: str) -> None:
        self.api_url = api_url
        self.session_id: str | None = None

    async def create_session(self) -> bool:
        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                resp = await client.post(f"{self.api_url}/sessions")
                resp.raise_for_status()
                self.session_id = resp.json()["session_id"]
                _log("system", f"session {self.session_id[:8]} ready")
                return True
        except Exception as e:
            _log("system", f"cannot reach API at {self.api_url}: {e}", "error")
            return False

    async def send_stream(self, message: str) -> None:
        if not self.session_id:
            _log("system", "no active session — use /new", "error")
            return
        url = f"{self.api_url}/sessions/{self.session_id}/messages"
        final_text = ""
        try:
            async with httpx.AsyncClient(timeout=300.0) as client:
                async with client.stream("POST", url, json={"message": message, "stream": True}) as resp:
                    resp.raise_for_status()
                    async for line in resp.aiter_lines():
                        if not line.startswith("data: "):
                            continue
                        event = json.loads(line[6:])
                        etype = event.get("type")
                        if etype == "tool_call":
                            _console.print(f"  [dim]⏺ {event['name']}[/dim]")
                        elif etype == "text":
                            final_text = event.get("content", "")
                        elif etype == "error":
                            _log("system", event.get("message", "unknown error"), "error")
                        elif etype == "done":
                            await resp.aclose()
                            break
        except httpx.HTTPStatusError as e:
            _log("system", f"API error {e.response.status_code}: {e.response.text}", "error")
            return
        except Exception as e:
            _log("system", str(e), "error")
            return
        if final_text:
            _print_agent(final_text)


class ServiceAgentTUI:
    def __init__(self, api_url: str) -> None:
        self.client = AgentClient(api_url)

    async def run(self) -> None:
        _print_welcome(self.client.api_url)
        await self.client.create_session()
        loop = asyncio.get_running_loop()
        while True:
            _console.print("  [#cc785c]>[/#cc785c] ", end="")
            try:
                raw = await loop.run_in_executor(None, _read_stdin)
            except (EOFError, KeyboardInterrupt):
                break
            if raw is None:
                break
            text = raw.strip()
            if not text:
                continue
            if text.lower() in ("/quit", "/exit", "quit", "exit"):
                break
            if text.startswith("/"):
                await self._slash(text)
            else:
                await self.client.send_stream(text)
        _console.print()
        _sys("bye")

    async def _slash(self, text: str) -> None:
        cmd = text.lower().split()[0]
        if cmd == "/new":
            _console.print()
            await self.client.create_session()
            _console.print()
        elif cmd == "/clear":
            _console.clear()
        else:
            _sys(f"unknown command: {cmd}")
            _sys("available: /new  /clear  /quit")
            _console.print()


def _read_stdin() -> str | None:
    try:
        line = sys.stdin.readline()
        return line.rstrip("\n") if line else None
    except (EOFError, KeyboardInterrupt):
        return None


def main() -> None:
    parser = argparse.ArgumentParser(description=f"{_NAME} TUI")
    parser.add_argument("--api-url", default=_DEFAULT_API_URL)
    args = parser.parse_args()
    try:
        asyncio.run(ServiceAgentTUI(api_url=args.api_url).run())
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
