"""
Generic Gemini service agent — agentic loop shared by all service agents.
DO NOT EDIT this file. Configure your agent in prompts.py and tools.py.
"""

import asyncio
import json
import os
from typing import AsyncIterator

import google.genai as genai
from google.genai import types

from .prompts import SYSTEM_PROMPT
from .tools import TOOL_DEFINITIONS, TOOL_FUNCTIONS


def _build_tools() -> types.Tool:
    return types.Tool(function_declarations=[
        types.FunctionDeclaration(
            name=t["name"],
            description=t["description"],
            parameters=t["parameters"],
        )
        for t in TOOL_DEFINITIONS
    ])


def _dispatch(name: str, args: dict) -> str:
    if name not in TOOL_FUNCTIONS:
        return json.dumps({"error": f"Unknown tool: {name}"})
    try:
        return json.dumps(TOOL_FUNCTIONS[name](args), ensure_ascii=False)
    except Exception as e:
        return json.dumps({"error": str(e)})


def _to_contents(history: list[dict]) -> list[types.Content]:
    out = []
    for msg in history:
        parts = [types.Part(text=p["text"]) for p in msg.get("parts", []) if "text" in p]
        if parts:
            out.append(types.Content(role=msg["role"], parts=parts))
    return out


def _from_contents(contents: list[types.Content]) -> list[dict]:
    history = []
    for c in contents:
        parts = []
        for p in c.parts:
            if hasattr(p, "text") and p.text:
                parts.append({"text": p.text})
            elif p.function_call:
                parts.append({"function_call": {"name": p.function_call.name, "args": dict(p.function_call.args)}})
            elif p.function_response:
                parts.append({"function_response": {"name": p.function_response.name, "response": p.function_response.response}})
        if parts:
            history.append({"role": c.role, "parts": parts})
    return history


class ServiceAgent:
    """Generic stateless agent. Session history is managed by the API layer."""

    MODEL = "gemini-2.5-pro"

    def __init__(self):
        api_key = os.environ.get("GOOGLE_API_KEY") or os.environ.get("GEMINI_API_KEY")
        if not api_key:
            raise ValueError("GOOGLE_API_KEY or GEMINI_API_KEY must be set.")
        self._client = genai.Client(api_key=api_key)
        self._tools = _build_tools()

    def _config(self) -> types.GenerateContentConfig:
        return types.GenerateContentConfig(
            system_instruction=SYSTEM_PROMPT,
            tools=[self._tools],
            temperature=0.2,
            max_output_tokens=8192,
        )

    def chat(self, history: list[dict], message: str) -> tuple[str, list[dict]]:
        """Synchronous agentic loop. Returns (text, updated_history)."""
        contents = _to_contents(history)
        contents.append(types.Content(role="user", parts=[types.Part(text=message)]))

        while True:
            resp = self._client.models.generate_content(
                model=self.MODEL, contents=contents, config=self._config()
            )
            model_content = resp.candidates[0].content
            contents.append(model_content)

            calls = [p for p in model_content.parts if p.function_call]
            if not calls:
                text = "\n".join(p.text for p in model_content.parts if hasattr(p, "text") and p.text).strip()
                return text, _from_contents(contents)

            tool_parts = []
            for p in calls:
                fc = p.function_call
                tool_parts.append(types.Part(
                    function_response=types.FunctionResponse(
                        name=fc.name,
                        response={"result": _dispatch(fc.name, dict(fc.args))},
                    )
                ))
            contents.append(types.Content(role="user", parts=tool_parts))

    async def stream_chat(self, history: list[dict], message: str) -> AsyncIterator[dict]:
        """
        Async generator yielding SSE events:
          {"type": "tool_call", "name": "...", "args": {...}}
          {"type": "tool_result", "name": "...", "result": "..."}
          {"type": "text", "content": "...", "history": [...]}
          {"type": "done"}
        """
        loop = asyncio.get_running_loop()
        contents = _to_contents(history)
        contents.append(types.Content(role="user", parts=[types.Part(text=message)]))

        while True:
            resp = await loop.run_in_executor(
                None,
                lambda c=list(contents): self._client.models.generate_content(
                    model=self.MODEL, contents=c, config=self._config()
                ),
            )
            model_content = resp.candidates[0].content
            contents.append(model_content)

            calls = [p for p in model_content.parts if p.function_call]
            if not calls:
                text = "\n".join(p.text for p in model_content.parts if hasattr(p, "text") and p.text).strip()
                yield {"type": "text", "content": text, "history": _from_contents(contents)}
                yield {"type": "done"}
                return

            tool_parts = []
            for p in calls:
                fc = p.function_call
                args = dict(fc.args)
                yield {"type": "tool_call", "name": fc.name, "args": args}
                result = await loop.run_in_executor(None, lambda n=fc.name, a=args: _dispatch(n, a))
                yield {"type": "tool_result", "name": fc.name, "result": result}
                tool_parts.append(types.Part(
                    function_response=types.FunctionResponse(
                        name=fc.name,
                        response={"result": result},
                    )
                ))
            contents.append(types.Content(role="user", parts=tool_parts))
